In [1]:
import os, sys
sys.path.insert(0, os.path.abspath("../../../Generic-Parallel-Compute-Helper/"))
from memory_compute import *

install_memory_guard()

[memory_guard] hard cap 13.3G virtual on this kernel (total RAM 14.8G, 6.6G free now). Runaway allocations fail cleanly; bounded streaming keeps normal work well under this.

14298132480

In [2]:
import os
import sys
import numpy as np
import pandas as pd

sys.path.append(os.path.abspath("../../"))
from EPF import variables
from EPF.variables import CITY, ALL_CITIES, OTHER_CITIES

## Weather is observed hourly data. The active feature blocks use only the latest observation available at the forecast origin, carried forward causally to the 5-minute grid. The optional forward-looking forecast-proxy block stays disabled.
### FCAST_24H = variables.PER_DAY        # 288
### FCAST_48H = 2 * variables.PER_DAY    # 576

In [3]:
def _wx(df: pd.DataFrame, var: str, city: str) -> pd.Series:
    """Weather variable series for a city, or NaN if that column is absent."""
    col = f"{var}_{city}"
    return df[col] if col in df.columns else pd.Series(np.nan, index=df.index)

In [4]:
df = read_parquet_float32("../1_Dataset/Processed_data/5_weather.parquet")

# Compatibility guard for processed weather files created before causal
# resampling was introduced. Exact-hour rows contain the original observations;
# rebuild every intra-hour row from the latest exact-hour value so this notebook
# cannot consume the old linear interpolation between current and future hours.
weather_index = df.index
hourly_observations = df.loc[(weather_index.minute == 0) & (weather_index.second == 0)]
df = hourly_observations.reindex(weather_index).ffill()
del hourly_observations, weather_index

df_core_columns = df.columns
df_base = df
df_base[:10]

Loading..:   0%|          | 0/10 [00:00<?, ?batch/s]

Loading..: 100%|██████████| 10/10 [00:01<00:00,  9.08batch/s]

,temp_sydney,feelslike_sydney,dew_sydney,humidity_sydney,precip_sydney,precipprob_sydney,snow_sydney,snowdepth_sydney,windgust_sydney,windspeed_sydney,...,windspeed_adelaide,winddir_adelaide,sealevelpressure_adelaide,cloudcover_adelaide,visibility_adelaide,solarradiation_adelaide,solarenergy_adelaide,uvindex_adelaide,severerisk_adelaide,stations_adelaide
SETTLEMENTDATE,,,,,,,,,,,,,,,,,,,,,
2018-01-01 00:00:00,22.4,22.4,18.299999,77.779999,0.0,0.0,0.0,0.0,28.799999,1.7,...,8.1,127.0,1010.799988,6.7,10.0,0.0,0.0,0.0,NaN,NaN
2018-01-01 00:05:00,22.4,22.4,18.299999,77.779999,0.0,0.0,0.0,0.0,28.799999,1.7,...,8.1,127.0,1010.799988,6.7,10.0,0.0,0.0,0.0,NaN,NaN
2018-01-01 00:10:00,22.4,22.4,18.299999,77.779999,0.0,0.0,0.0,0.0,28.799999,1.7,...,8.1,127.0,1010.799988,6.7,10.0,0.0,0.0,0.0,NaN,NaN
2018-01-01 00:15:00,22.4,22.4,18.299999,77.779999,0.0,0.0,0.0,0.0,28.799999,1.7,...,8.1,127.0,1010.799988,6.7,10.0,0.0,0.0,0.0,NaN,NaN
2018-01-01 00:20:00,22.4,22.4,18.299999,77.779999,0.0,0.0,0.0,0.0,28.799999,1.7,...,8.1,127.0,1010.799988,6.7,10.0,0.0,0.0,0.0,NaN,NaN
2018-01-01 00:25:00,22.4,22.4,18.299999,77.779999,0.0,0.0,0.0,0.0,28.799999,1.7,...,8.1,127.0,1010.799988,6.7,10.0,0.0,0.0,0.0,NaN,NaN
2018-01-01 00:30:00,22.4,22.4,18.299999,77.779999,0.0,0.0,0.0,0.0,28.799999,1.7,...,8.1,127.0,1010.799988,6.7,10.0,0.0,0.0,0.0,NaN,NaN
2018-01-01 00:35:00,22.4,22.4,18.299999,77.779999,0.0,0.0,0.0,0.0,28.799999,1.7,...,8.1,127.0,1010.799988,6.7,10.0,0.0,0.0,0.0,NaN,NaN
2018-01-01 00:40:00,22.4,22.4,18.299999,77.779999,0.0,0.0,0.0,0.0,28.799999,1.7,...,8.1,127.0,1010.799988,6.7,10.0,0.0,0.0,0.0,NaN,NaN
2018-01-01 00:45:00,22.4,22.4,18.299999,77.779999,0.0,0.0,0.0,0.0,28.799999,1.7,...,8.1,127.0,1010.799988,6.7,10.0,0.0,0.0,0.0,NaN,NaN

In [5]:
def _add_weather_now_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Current-interval weather for the target region's reference city plus derived
    cooling/heating degrees. Hot afternoons drive air-conditioning demand while
    cold snaps drive heating; both lift price. Every value is the latest hourly
    observation available by the interval, so no later observation is used.
    Returns only the new columns to avoid copying the full base frame.
    """
    C = CITY
    t = _wx(df, "temp", C)
    new_cols = {}
    new_cols[f"temp_{C}_now"]       = t.astype(np.float32)
    new_cols[f"cdd_{C}"]            = (t - 18).clip(lower=0).astype(np.float32)
    new_cols[f"hdd_{C}"]            = (18 - t).clip(lower=0).astype(np.float32)
    new_cols[f"feelslike_{C}_now"]  = _wx(df, "feelslike", C).astype(np.float32)
    new_cols[f"humidity_{C}_now"]   = _wx(df, "humidity", C).astype(np.float32)
    new_cols[f"windspeed_{C}_now"]  = _wx(df, "windspeed", C).astype(np.float32)
    new_cols[f"windgust_{C}_now"]   = _wx(df, "windgust", C).astype(np.float32)
    new_cols[f"solarrad_{C}_now"]   = _wx(df, "solarradiation", C).astype(np.float32)
    new_cols[f"cloudcover_{C}_now"] = _wx(df, "cloudcover", C).astype(np.float32)
    return pd.DataFrame(new_cols, index=df.index)


new_df = _add_weather_now_features(df_base)
df = pd.concat([df, new_df], axis=1)
new_df[:10]

,temp_sydney_now,cdd_sydney,hdd_sydney,feelslike_sydney_now,humidity_sydney_now,windspeed_sydney_now,windgust_sydney_now,solarrad_sydney_now,cloudcover_sydney_now
SETTLEMENTDATE,,,,,,,,,
2018-01-01 00:00:00,22.4,4.4,0.0,22.4,77.779999,1.7,28.799999,0.0,91.599998
2018-01-01 00:05:00,22.4,4.4,0.0,22.4,77.779999,1.7,28.799999,0.0,91.599998
2018-01-01 00:10:00,22.4,4.4,0.0,22.4,77.779999,1.7,28.799999,0.0,91.599998
2018-01-01 00:15:00,22.4,4.4,0.0,22.4,77.779999,1.7,28.799999,0.0,91.599998
2018-01-01 00:20:00,22.4,4.4,0.0,22.4,77.779999,1.7,28.799999,0.0,91.599998
2018-01-01 00:25:00,22.4,4.4,0.0,22.4,77.779999,1.7,28.799999,0.0,91.599998
2018-01-01 00:30:00,22.4,4.4,0.0,22.4,77.779999,1.7,28.799999,0.0,91.599998
2018-01-01 00:35:00,22.4,4.4,0.0,22.4,77.779999,1.7,28.799999,0.0,91.599998
2018-01-01 00:40:00,22.4,4.4,0.0,22.4,77.779999,1.7,28.799999,0.0,91.599998
2018-01-01 00:45:00,22.4,4.4,0.0,22.4,77.779999,1.7,28.799999,0.0,91.599998

In [6]:
def _add_weather_history_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Backward-looking weather regime for the target city: temperature lags, daily
    rolling level/extremes, accumulated cooling/heating degree-hours and recent
    wind. Captures heat build-up and cold spells. Look-back only, no leakage.
    Returns only the new columns to avoid copying the full base frame.
    """
    C = CITY
    t = _wx(df, "temp", C)
    cdd = (t - 18).clip(lower=0)
    hdd = (18 - t).clip(lower=0)
    new_cols = {}
    for lag in [variables.PER_HOUR, variables.PER_DAY]:
        new_cols[f"temp_{C}_lag_{lag}"] = t.shift(lag).astype(np.float32)
    new_cols[f"temp_{C}_rmean_{variables.PER_DAY}"] = t.rolling(variables.PER_DAY, min_periods=variables.PER_HOUR).mean().astype(np.float32)
    new_cols[f"temp_{C}_rmax_{variables.PER_DAY}"]  = t.rolling(variables.PER_DAY, min_periods=variables.PER_HOUR).max().astype(np.float32)
    new_cols[f"temp_{C}_rmin_{variables.PER_DAY}"]  = t.rolling(variables.PER_DAY, min_periods=variables.PER_HOUR).min().astype(np.float32)
    new_cols[f"cdd_{C}_rsum_24h"] = (cdd.rolling(variables.PER_DAY, min_periods=variables.PER_HOUR).sum() / variables.PER_HOUR).astype(np.float32)
    new_cols[f"hdd_{C}_rsum_24h"] = (hdd.rolling(variables.PER_DAY, min_periods=variables.PER_HOUR).sum() / variables.PER_HOUR).astype(np.float32)
    new_cols[f"windspeed_{C}_rmean_{variables.PER_DAY}"] = (
        _wx(df, "windspeed", C).rolling(variables.PER_DAY, min_periods=variables.PER_HOUR).mean().astype(np.float32)
    )
    return pd.DataFrame(new_cols, index=df.index)


new_df = _add_weather_history_features(df_base)
df = pd.concat([df, new_df], axis=1)
new_df[:10]

,temp_sydney_lag_12,temp_sydney_lag_288,temp_sydney_rmean_288,temp_sydney_rmax_288,temp_sydney_rmin_288,cdd_sydney_rsum_24h,hdd_sydney_rsum_24h,windspeed_sydney_rmean_288
SETTLEMENTDATE,,,,,,,,
2018-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:10:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:20:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:25:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:35:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:40:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# def _add_weather_forecast_features(df: pd.DataFrame) -> pd.DataFrame:
#     """
#     Forward-looking weather over the next 24h / 48h for the target city, used as
#     a perfect-foresight proxy for the weather *forecast* a real operator would
#     hold at run time (the model's price horizon is 48h). Expected temperature,
#     cooling/heating degree-hours, solar irradiance and wind over the horizon are
#     the primary drivers of demand and variable-renewable output. Tagged "_fcast".
#     """
#     df = df.copy()
#     C = CITY
#     t = _wx(df, "temp", C)
#     cdd = (t - 18).clip(lower=0)
#     hdd = (18 - t).clip(lower=0)
#     solar = _wx(df, "solarradiation", C)
#     wind = _wx(df, "windspeed", C)
#     new_cols = {}
#     for w, lab in [(FCAST_24H, "24h"), (FCAST_48H, "48h")]:
#         new_cols[f"temp_{C}_fcast_mean_{lab}"]      = _fwd_mean(t, w)
#         new_cols[f"temp_{C}_fcast_max_{lab}"]       = t.rolling(w, min_periods=1).max().shift(-(w - 1)).astype(np.float32)
#         new_cols[f"cdd_{C}_fcast_sum_{lab}"]        = (_fwd_sum(cdd, w) / variables.PER_HOUR).astype(np.float32)
#         new_cols[f"hdd_{C}_fcast_sum_{lab}"]        = (_fwd_sum(hdd, w) / variables.PER_HOUR).astype(np.float32)
#         new_cols[f"solarrad_{C}_fcast_mean_{lab}"]  = _fwd_mean(solar, w)
#         new_cols[f"windspeed_{C}_fcast_mean_{lab}"] = _fwd_mean(wind, w)
#     return pd.concat([df, pd.DataFrame(new_cols, index=df.index)], axis=1)


# new_df = _add_weather_forecast_features(df_base)
# df = pd.concat([df, new_df.drop(columns=df_core_columns)], axis=1)
# new_df[:10]

In [8]:
def _add_cross_city_weather_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    National weather context and the other capital cities' conditions.
    Coincident heat across the NEM lifts demand everywhere and correlates VRE
    output, tightening the interconnected market. Latest-known values only.
    Returns only the new columns to avoid copying the full base frame.
    """
    new_cols = {}
    nat_temp = pd.concat([_wx(df, "temp", c) for c in ALL_CITIES], axis=1).mean(axis=1)
    new_cols["nat_temp_mean"] = nat_temp.astype(np.float32)
    new_cols["nat_cdd_mean"]  = (nat_temp - 18).clip(lower=0).astype(np.float32)
    new_cols["nat_hdd_mean"]  = (18 - nat_temp).clip(lower=0).astype(np.float32)
    for c in OTHER_CITIES:
        new_cols[f"temp_{c}_now"]      = _wx(df, "temp", c).astype(np.float32)
        new_cols[f"solarrad_{c}_now"]  = _wx(df, "solarradiation", c).astype(np.float32)
        new_cols[f"windspeed_{c}_now"] = _wx(df, "windspeed", c).astype(np.float32)
    return pd.DataFrame(new_cols, index=df.index)


new_df = _add_cross_city_weather_features(df_base)
df = pd.concat([df, new_df], axis=1)
new_df[:10]

,nat_temp_mean,nat_cdd_mean,nat_hdd_mean,temp_brisbane_now,solarrad_brisbane_now,windspeed_brisbane_now,temp_melbourne_now,solarrad_melbourne_now,windspeed_melbourne_now,temp_adelaide_now,solarrad_adelaide_now,windspeed_adelaide_now
SETTLEMENTDATE,,,,,,,,,,,,
2018-01-01 00:00:00,20.15,2.15,0.0,25.4,0.0,1.9,17.4,0.0,6.4,15.4,0.0,8.1
2018-01-01 00:05:00,20.15,2.15,0.0,25.4,0.0,1.9,17.4,0.0,6.4,15.4,0.0,8.1
2018-01-01 00:10:00,20.15,2.15,0.0,25.4,0.0,1.9,17.4,0.0,6.4,15.4,0.0,8.1
2018-01-01 00:15:00,20.15,2.15,0.0,25.4,0.0,1.9,17.4,0.0,6.4,15.4,0.0,8.1
2018-01-01 00:20:00,20.15,2.15,0.0,25.4,0.0,1.9,17.4,0.0,6.4,15.4,0.0,8.1
2018-01-01 00:25:00,20.15,2.15,0.0,25.4,0.0,1.9,17.4,0.0,6.4,15.4,0.0,8.1
2018-01-01 00:30:00,20.15,2.15,0.0,25.4,0.0,1.9,17.4,0.0,6.4,15.4,0.0,8.1
2018-01-01 00:35:00,20.15,2.15,0.0,25.4,0.0,1.9,17.4,0.0,6.4,15.4,0.0,8.1
2018-01-01 00:40:00,20.15,2.15,0.0,25.4,0.0,1.9,17.4,0.0,6.4,15.4,0.0,8.1
2018-01-01 00:45:00,20.15,2.15,0.0,25.4,0.0,1.9,17.4,0.0,6.4,15.4,0.0,8.1

In [9]:
# Retain core columns: each 5-minute row holds only the latest hourly observation
# available at t. The forward-looking _fcast block stays disabled.
print("Total features:", df.shape[1])
df.to_parquet("../2_Features_build/Feature_data/5_weather.parquet")
df.shape

Total features: 104

(902581, 104)

In [10]:
# Free this kernel's memory so the next notebook has RAM to work with
# (clears data variables + returns freed heap to the OS).
release_memory()

[release_memory] cleared 12 variable(s); kernel rss 0.55G, 6.1G RAM free now